# Configure Eureka Server
server:
  port: 8010

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85