spring:
  application:
    name: zuul-server
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

server:
  port: ${random.int(8000,8100)}

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  sensitive-headers:
  routes:
    BoostMS:
      path: /api/boost/**
      service-id: BoostMS
    EngineMS:
      path: /api/engine/**
      service-id: EngineMS
    HandlingMS:
      path: /api/handling/**
      service-id: HandlingMS
    ManufacturerMS:
      path: /api/manufacturer/**
      service-id: ManufacturerMS
    TransmissionMS:
      path: /api/transmission/**
      service-id: TransmissionMS
    BuilderMS:
      path: /builder/**
      service-id: BuilderMS
  host:
    connection-request-timeout-millis: 30000
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, builder, api, actuator