# Configure Eureka Server
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: EngineMS
  codec:
    max-in-memory-size: 1MB